package model.pojo;
// Generated 17 Oct, 2017 2:26:18 AM by Hibernate Tools 3.6.0



/**
 * EmpInfo generated by hbm2java
 */
public class EmpInfo  implements java.io.Serializable {


     private Integer id;
     private String empName;

    public EmpInfo() {
    }

    public EmpInfo(String empName) {
       this.empName = empName;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }




}


